version: '3.8'

services:
  app:
    container_name: varsani_hemal_coding_assignment11
    build:
      context: .
      target: development
    volumes:
      - .:/varsani_hemal_site
      - /varsani_hemal_site/node_modules
    ports:
      - "7775:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
